### ISSUE TITLE
Klikken op naam in informatiescherm kom je terug bij de geselecteerde DBK

### ISSUE THREAD

**Issue by DenCop** [dogodigi/opendispatcher#275]
Als je op de naam in de DBK informatiescherm klikt kom je terug bij de plek van de DBK:

![image](https://f.cloud.github.com/assets/6464531/2377174/736eccf8-a87f-11e3-8e37-caded558aec9.png)

Dus op vrijetijds centrum de Parel.

Heb je misschien een beter idee?

**Comment by milovanderlinden** [comment]
Fixed in 3.0
