### ISSUE TITLE
Toevoegen cascaded WMS

### ISSUE THREAD

**Issue by DenCop** [dogodigi/opendispatcher#298]
In vrz geoserver een bron toegevoegd voor een WMS bron:

![image](https://cloud.githubusercontent.com/assets/6464531/2588120/0491f384-ba34-11e3-8420-1d06202eef46.png)

Hierna een laag toegevoegd:
![image](https://cloud.githubusercontent.com/assets/6464531/2588123/2439f100-ba34-11e3-8c64-b02de31bb4e0.png)

In Mapinfo krijg ik wel beeld:
![image](https://cloud.githubusercontent.com/assets/6464531/2588153/c338e43c-ba34-11e3-81df-c8738444def4.png)

in geoserver krijg ik een kapotte tegel:
![image](https://cloud.githubusercontent.com/assets/6464531/2588157/d7229736-ba34-11e3-8904-6ccd1f15d5c5.png)

Wat doe ik fout?

**Comment by milovanderlinden** [comment]
Resolved
