### ISSUE TITLE
Symbolen landelijke legenda Natuurbrandbestrijding

### ISSUE THREAD

**Issue by Pleuni** [dogodigi/opendispatcher#313]
Vanuit de landelijke vakgroep natuurbrand zijn we bezig een landelijk legenda te maken voor natuurbrandbestrijding. In de bijlage staan een aantal symbolen en laagaanduidingen die nog gewenst zijn (zie bijlage).
Ziet iemand mogelijkheden om hier aan te komen? Ik hoor het graag. 
![page0001](https://cloud.githubusercontent.com/assets/6481957/3287077/ce98395a-f552-11e3-82e6-f35d35613bf8.jpg)
![page0002](https://cloud.githubusercontent.com/assets/6481957/3287078/ce992298-f552-11e3-9a9b-a58e13665ab6.jpg)
![page0003](https://cloud.githubusercontent.com/assets/6481957/3287079/ce9998c2-f552-11e3-931c-883e4b038b23.jpg)
![page0004](https://cloud.githubusercontent.com/assets/6481957/3287080/ce9a21d4-f552-11e3-9081-3571cfd0c32b.jpg)
![page0005](https://cloud.githubusercontent.com/assets/6481957/3287081/ce9a5866-f552-11e3-82ed-badf62d06a29.jpg)

**Comment by milovanderlinden** [comment]
Should be fixed in Geoserver layer configuration
