### ISSUE TITLE
Dubbele tekstweergave

### ISSUE THREAD

**Issue by Pleuni** [dogodigi/opendispatcher#380]
Bij de selectie "naburige DBK's" wordt de tekst dubbel weergegeven in de viewer.

![dubb tekst 1](https://cloud.githubusercontent.com/assets/6481957/4353922/1226a2aa-4239-11e4-9eed-a73174ea67b6.JPG)
![dubb tekst 2](https://cloud.githubusercontent.com/assets/6481957/4353923/1227a6d2-4239-11e4-8e71-afbb21a77060.JPG)

**Comment by milovanderlinden** [comment]
Solved. This function should not be used anymore.
