### ISSUE TITLE
Move alternative communication infrastructure to existing tab

### ISSUE THREAD

**Issue by milovanderlinden** [dogodigi/opendispatcher#427]
See #425. Alternative communication infrastructure information now covers a seperate tab in the information dialog. @dencop requested it to be moved elsewhere. Requesting details.

**Comment by DenCop** [comment]
Symbolen hoeven niet terug te komen in Informatiescherm. Alleen bij aanklikken moet de extra informatie getoond worden.

**Comment by milovanderlinden** [comment]
Ah, clear.
